version: '3.8'

services:
  backend:
    build:
      context: ./backendside
    ports:
      - "8080:8080"
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - PORT=8080

  frontend:
    build:
      context: ./frontendside
    ports:
      - "3000:3000"
    depends_on:
      - backend
